/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplesIndexRouteImport } from './routes/temples.index'
import { Route as TemplesIdRouteImport } from './routes/temples.$id'
import { Route as SlotsIdRouteImport } from './routes/slots.$id'
import { Route as OrganizerTemplesRouteImport } from './routes/organizer.temples'
import { Route as OrganizerSlotsRouteImport } from './routes/organizer.slots'
import { Route as OrganizerDonationsRouteImport } from './routes/organizer.donations'
import { Route as OrganizerDashboardRouteImport } from './routes/organizer.dashboard'
import { Route as OrganizerBookingsRouteImport } from './routes/organizer.bookings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemplesRouteImport } from './routes/admin.temples'
import { Route as AdminSlotsRouteImport } from './routes/admin.slots'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOrganizersRouteImport } from './routes/admin.organizers'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesIndexRoute = TemplesIndexRouteImport.update({
  id: '/temples/',
  path: '/temples/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesIdRoute = TemplesIdRouteImport.update({
  id: '/temples/$id',
  path: '/temples/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsIdRoute = SlotsIdRouteImport.update({
  id: '/slots/$id',
  path: '/slots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerTemplesRoute = OrganizerTemplesRouteImport.update({
  id: '/organizer/temples',
  path: '/organizer/temples',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerSlotsRoute = OrganizerSlotsRouteImport.update({
  id: '/organizer/slots',
  path: '/organizer/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDonationsRoute = OrganizerDonationsRouteImport.update({
  id: '/organizer/donations',
  path: '/organizer/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/organizer/dashboard',
  path: '/organizer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerBookingsRoute = OrganizerBookingsRouteImport.update({
  id: '/organizer/bookings',
  path: '/organizer/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplesRoute = AdminTemplesRouteImport.update({
  id: '/admin/temples',
  path: '/admin/temples',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/admin/slots',
  path: '/admin/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizersRoute = AdminOrganizersRouteImport.update({
  id: '/admin/organizers',
  path: '/admin/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/admin/donations',
  path: '/admin/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/organizers': typeof AdminOrganizersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/temples': typeof AdminTemplesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizer/bookings': typeof OrganizerBookingsRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/donations': typeof OrganizerDonationsRoute
  '/organizer/slots': typeof OrganizerSlotsRoute
  '/organizer/temples': typeof OrganizerTemplesRoute
  '/slots/$id': typeof SlotsIdRoute
  '/temples/$id': typeof TemplesIdRoute
  '/temples/': typeof TemplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/organizers': typeof AdminOrganizersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/temples': typeof AdminTemplesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizer/bookings': typeof OrganizerBookingsRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/donations': typeof OrganizerDonationsRoute
  '/organizer/slots': typeof OrganizerSlotsRoute
  '/organizer/temples': typeof OrganizerTemplesRoute
  '/slots/$id': typeof SlotsIdRoute
  '/temples/$id': typeof TemplesIdRoute
  '/temples': typeof TemplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/organizers': typeof AdminOrganizersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/temples': typeof AdminTemplesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizer/bookings': typeof OrganizerBookingsRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/donations': typeof OrganizerDonationsRoute
  '/organizer/slots': typeof OrganizerSlotsRoute
  '/organizer/temples': typeof OrganizerTemplesRoute
  '/slots/$id': typeof SlotsIdRoute
  '/temples/$id': typeof TemplesIdRoute
  '/temples/': typeof TemplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookings'
    | '/contact'
    | '/dashboard'
    | '/donations'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/donations'
    | '/admin/organizers'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/slots'
    | '/admin/temples'
    | '/admin/users'
    | '/organizer/bookings'
    | '/organizer/dashboard'
    | '/organizer/donations'
    | '/organizer/slots'
    | '/organizer/temples'
    | '/slots/$id'
    | '/temples/$id'
    | '/temples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookings'
    | '/contact'
    | '/dashboard'
    | '/donations'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/donations'
    | '/admin/organizers'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/slots'
    | '/admin/temples'
    | '/admin/users'
    | '/organizer/bookings'
    | '/organizer/dashboard'
    | '/organizer/donations'
    | '/organizer/slots'
    | '/organizer/temples'
    | '/slots/$id'
    | '/temples/$id'
    | '/temples'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookings'
    | '/contact'
    | '/dashboard'
    | '/donations'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/donations'
    | '/admin/organizers'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/slots'
    | '/admin/temples'
    | '/admin/users'
    | '/organizer/bookings'
    | '/organizer/dashboard'
    | '/organizer/donations'
    | '/organizer/slots'
    | '/organizer/temples'
    | '/slots/$id'
    | '/temples/$id'
    | '/temples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonationsRoute: typeof DonationsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminOrganizersRoute: typeof AdminOrganizersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminTemplesRoute: typeof AdminTemplesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OrganizerBookingsRoute: typeof OrganizerBookingsRoute
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  OrganizerDonationsRoute: typeof OrganizerDonationsRoute
  OrganizerSlotsRoute: typeof OrganizerSlotsRoute
  OrganizerTemplesRoute: typeof OrganizerTemplesRoute
  SlotsIdRoute: typeof SlotsIdRoute
  TemplesIdRoute: typeof TemplesIdRoute
  TemplesIndexRoute: typeof TemplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/': {
      id: '/temples/'
      path: '/temples'
      fullPath: '/temples/'
      preLoaderRoute: typeof TemplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/$id': {
      id: '/temples/$id'
      path: '/temples/$id'
      fullPath: '/temples/$id'
      preLoaderRoute: typeof TemplesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots/$id': {
      id: '/slots/$id'
      path: '/slots/$id'
      fullPath: '/slots/$id'
      preLoaderRoute: typeof SlotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/temples': {
      id: '/organizer/temples'
      path: '/organizer/temples'
      fullPath: '/organizer/temples'
      preLoaderRoute: typeof OrganizerTemplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/slots': {
      id: '/organizer/slots'
      path: '/organizer/slots'
      fullPath: '/organizer/slots'
      preLoaderRoute: typeof OrganizerSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/donations': {
      id: '/organizer/donations'
      path: '/organizer/donations'
      fullPath: '/organizer/donations'
      preLoaderRoute: typeof OrganizerDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/dashboard': {
      id: '/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/bookings': {
      id: '/organizer/bookings'
      path: '/organizer/bookings'
      fullPath: '/organizer/bookings'
      preLoaderRoute: typeof OrganizerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/temples': {
      id: '/admin/temples'
      path: '/admin/temples'
      fullPath: '/admin/temples'
      preLoaderRoute: typeof AdminTemplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/admin/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizers': {
      id: '/admin/organizers'
      path: '/admin/organizers'
      fullPath: '/admin/organizers'
      preLoaderRoute: typeof AdminOrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/admin/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonationsRoute: DonationsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminOrganizersRoute: AdminOrganizersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminTemplesRoute: AdminTemplesRoute,
  AdminUsersRoute: AdminUsersRoute,
  OrganizerBookingsRoute: OrganizerBookingsRoute,
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  OrganizerDonationsRoute: OrganizerDonationsRoute,
  OrganizerSlotsRoute: OrganizerSlotsRoute,
  OrganizerTemplesRoute: OrganizerTemplesRoute,
  SlotsIdRoute: SlotsIdRoute,
  TemplesIdRoute: TemplesIdRoute,
  TemplesIndexRoute: TemplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
